version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: build docker image
          command: |
            docker build --tag "${HEROKU_CONTAINER_REGISTRY}" .
